# Generated by Django 5.2 on 2025-05-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_vendor_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourusr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('contact', models.IntegerField(default=0, max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField()),
            ],
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='package',
        ),
        migrations.AddField(
            model_name='vendor',
            name='password',
            field=models.CharField(default=0),
        ),
    ]
