# Generated by Django 5.2 on 2025-05-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_tourusr_remove_vendor_package_vendor_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('days', models.IntegerField()),
            ],
        ),
    ]
