# Generated by Django 5.2 on 2025-05-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_packreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='packreg',
            name='package',
            field=models.TextField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='packreg',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='packreg',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
