# Generated by Django 5.2 on 2025-05-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_packreg_package_alter_packreg_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packreg',
            name='amount',
            field=models.IntegerField(max_length=500, null=0),
        ),
        migrations.AlterField(
            model_name='packreg',
            name='days',
            field=models.IntegerField(max_length=500, null=0),
        ),
        migrations.AlterField(
            model_name='packreg',
            name='package',
            field=models.TextField(max_length=500),
        ),
    ]
