# Generated by Django 5.2 on 2025-05-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0007_alter_packreg_amount_alter_packreg_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packreg',
            name='amount',
            field=models.IntegerField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='packreg',
            name='days',
            field=models.IntegerField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tourusr',
            name='contact',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
