# Generated by Django 5.2 on 2025-05-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0008_alter_packreg_amount_alter_packreg_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packreg',
            name='adm',
            field=models.IntegerField(default=0),
        ),
    ]
