# Generated by Django 5.2 on 2025-05-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0009_packreg_adm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packreg',
            name='adm',
        ),
        migrations.AddField(
            model_name='packreg',
            name='admin',
            field=models.IntegerField(default=0),
        ),
    ]
