# Generated by Django 5.2 on 2025-05-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0010_remove_packreg_adm_packreg_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packreg',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
