# Generated by Django 5.2 on 2025-05-20 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0011_alter_packreg_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packreg',
            name='admin',
        ),
    ]
