# Generated by Django 5.2 on 2025-05-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0012_remove_packreg_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packreg',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='packreg',
            name='days',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tourusr',
            name='contact',
            field=models.IntegerField(null=True),
        ),
    ]
