# Generated by Django 5.2 on 2025-05-20 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0014_packreg_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packreg',
            old_name='admin',
            new_name='approval',
        ),
    ]
