# Generated by Django 5.2 on 2025-06-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0017_newuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
        migrations.DeleteModel(
            name='Tourusr',
        ),
        migrations.RemoveField(
            model_name='packreg',
            name='img',
        ),
    ]
